"""Add created_at field to Job model

Revision ID: 32c51d93e7e6
Revises: ffd797af2c15
Create Date: 2025-05-09 14:45:18.194596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c51d93e7e6'
down_revision = 'ffd797af2c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
