"""Add company_url column to Job model

Revision ID: 4a13fa080447
Revises: 8db19f89b4b9
Create Date: 2025-05-15 11:12:54.620616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a13fa080447'
down_revision = '8db19f89b4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('company_url')

    # ### end Alembic commands ###
