"""Add created_at to job

Revision ID: 8db19f89b4b9
Revises: 32c51d93e7e6
Create Date: 2025-05-09 15:47:35.839980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db19f89b4b9'
down_revision = '32c51d93e7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
